config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  get 'dashboard/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users do
    post 'approve_user', on: :member
    post 'reject_user', on: :member
    get 'preview', on: :member
  end

  get 'home/index'
  get '/car_collection', to: 'home#car_collection', as: 'car_collection'
  get '/car_search', to: 'home#car_search', as: 'car_search'
  post '/verification', to: 'users#verification', as: 'verification'
  get '/user_verification', to: 'users#user_verification', as: 'user_verification'
  get '/dashboard', to: 'dashboard#index', as: 'dashboard'
  get '/car_purchase', to: 'cars#car_purchase', as: 'car_purchase'
  get '/successful_bid', to: 'cars#successful_bid', as: 'successful_bid'
  get '/about', to: 'home#about', as: 'about'
  get '/revenue', to: 'revenues#index', as: 'revenue'
  get '/download_reports', to: 'revenues#download_reports', as: 'download_reports'
  
  resources :cars do
    post 'add_to_auction', on: :member
    post 'buy'
    post 'submit_bid'
    get 'highest_bid'
  end

  scope module: 'payments' do
    get 'create_checkout_session'
    get 'subscription'
  end

  resources :auctions do
    get 'cars', on: :member
    delete 'delete_auction_car', on: :member
    collection do
      get 'all_auctions'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  mount Sidekiq::Web => '/sidekiq'
end

app/models/auction.rb
class Auction < ApplicationRecord
  has_many :auction_cars
  has_many :cars, through: :auction_cars
  has_many :bids

  scope :current, -> { where(status: "in_progress") }
  scope :pending, -> { where(status: "pending") }
  scope :completed, -> { where(status: "completed") }
  scope :completed_not_updated, -> { current.where('end_time < ?', Time.now) }

  def remove_car(car)
    self.cars.delete(car)
  end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :set_auction, only: %i[ show edit update destroy ]
  before_action :ensure_admin

  def index
    @auctions = Auction.current.or(Auction.pending)
    @live_auctions = Auction.current.includes(:auction_cars)
    @auction_cars = @live_auctions.map(&:auction_cars).flatten
    @auction_cars_paginated = Kaminari.paginate_array(@auction_cars).page(params[:live_auction_page]).per(5)
    @cars = Car.available.paginate(page: params[:page], per_page: 5)
    @cars_paginated = Car.available.paginate(page: params[:mcars_page], per_page: 1)
    @sold_cars = Car.sold_cars.paginate(page: params[:sold_page], per_page: 2)
  end
  
  def create
    @auction = Auction.new(auction_params)

    respond_to do |format|
      if @auction.save
        format.html { redirect_to auctions_path, notice: "Auction was successfully created." }
        format.json { render :show, status: :created, location: @auction }
      else
        format.html { redirect_to auctions_path, notice: "Auction was NOT created." }
      end
    end
  end

  def all_auctions
    if params[:search].present?
      @auctions = Auction.where("title LIKE ?", "%#{params[:search]}%").paginate(page: params[:page], per_page: 10)
    else
      @auctions = Auction.paginate(page: params[:page], per_page: 10)
    end
  end

  def cars
    @auction = Auction.find(params[:id])
    @cars = @auction.cars
    render partial: 'cars_list', locals: { cars: @cars }
  end

  def delete_auction_car
    @auction = Auction.find(params[:id])
    @car = @auction.cars.find(params[:car_id])
    if @auction.remove_car(@car)
      render json: { success: true, message: 'Car successfully removed from auction.' }
    else
      render json: { success: false, message: 'Failed to remove car from auction.' }, status: :unprocessable_entity
    end
  end

  # GET /auctions/1 or /auctions/1.json
  def show
  end

  # GET /auctions/new
  def new
    @auction = Auction.new
  end

  # GET /auctions/1/edit
  def edit
  end

  

  # PATCH/PUT /auctions/1 or /auctions/1.json
  def update
    respond_to do |format|
      if @auction.update(auction_params)
        format.html { redirect_to auction_url(@auction), notice: "Auction was successfully updated." }
        format.json { render :show, status: :ok, location: @auction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auctions/1 or /auctions/1.json
  def destroy
    @auction.destroy

    respond_to do |format|
      format.html { redirect_to auctions_url, notice: "Auction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_auction
      @auction = Auction.find(params[:id])
    end

    def auction_params
      params.require(:auction).permit(:title, :lot_no, :start_time, :end_time)
    end

    def ensure_admin
      authorize! :manage, Auction
    end
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/views/auctions/_auction.html.erb
<div id="<%= dom_id auction %>">
</div>

app/views/auctions/_cars_table.html.erb
<input type="hidden" id="selected-car-id" name="selected-car-id">
<div class="auction-cars-table">
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Tracking ID</th>
          <th>Product Name</th>
          <th>Reserve Price</th>
          <th>Buy Now Price</th>
          <th>Category</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @cars&.each do |car| %>
          <tr>
            <td><%= car.id%></td>
            <td>
              <div style="display: flex; align-items: center;">
                <% if car.image.attached? %>
                  <%= image_tag url_for(car.image), class: "mr-2", style: "width: 50px; height: 35px; margin-right: 5px;" %>
                <% else %>
                  <%= image_tag("no-image.jpg", alt: "no-image", class: "mr-2", style: "width: 50px; height: 35px; margin-right: 5px;") %>
                <% end %>
                <%= link_to "#{car.make}, #{car.model}", car_path(car), class: "car-name" %>      
              </div>
            </td>
            <td>£<%= car.reserve_auction_price%></td>
            <td>£<%= car.buy_now_price%></td>
            <td><%= car.salvage_category.name%> </td>
            <td>
              <button class="btn btn-primary add-to-auction" style="background: #2B4159; color: white; width: 100%;border: none; border-radius: 25px; height: 40px;" data-car-id="<%= car.id %>">Add To Auction</button>
            </td>
          </tr>
        <% end %>

        <% if @cars.blank? %>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= will_paginate @cars %>
</div>

<div class="car-display">
  <% @cars_paginated&.each do |car| %>
    <div style="background: aliceblue;" class="mobile-car">

      <div class="mobile-car-inner">
        <% if car.image.attached? %>
            <%= image_tag url_for(car.image), class: "", style: "max-width: 100%; width: 100%" %>
          <%else%>
            <%= image_tag("no-image.jpg", alt: "no-image", class: "", style: "max-width: 100%; width: 100%") %>
          <% end %> 
      </div>

      <div class="mobile-car-inner">
        <div style="flex: 1;">
          <div style="text-align: left; color: #646d81; font-size: larger;">Make and Model</div>
          <div style="text-align: left; color: #2B4159; font-size: x-large; font-weight: bold;"><%="#{car.make}, #{car.model}"%></div>
        </div>

        <div style="flex: 1;">
          <div style="text-align: right; color: #646d81; font-size: larger;">Fixed Price</div>
          <div style="text-align: right; color: #2B4159; font-size: x-large">£<%= car.reserve_auction_price%></div>
        </div>
      </div>

      <div class="mobile-car-inner">
        <div style="flex: 1;">
          <div style="text-align: left; color: #646d81; font-size: larger;">Buy Now Price</div>
          <div style="text-align: left; color: #2B4159; font-size: x-large; font-weight: bold;">£<%=car.buy_now_price%></div>
        </div>

        <div style="flex: 1;">
          <div style="text-align: right; color: #646d81; font-size: larger;">Category</div>
          <div style="text-align: right; color: #2B4159; font-size: x-large"><%= car.category.name%></div>
        </div>
      </div>

      <div class="mobile-car-inner button-container">
        <button class="btn btn-primary add-to-auction" style="background: #2B4159; color: white; width: 100%;border: none; border-radius: 25px; height: 40px;" data-car-id="<%= car.id %>">Add To Auction</button>
      </div>
    </div>
  <% end %>
  <%= will_paginate @cars_paginated, param_name: 'mcars_page' %>
</div>

<div class="modal fade" id="auctionModal" tabindex="-1" aria-labelledby="auctionModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div style="background: #F4F7FE;" class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="auctionModalLabel">Available Auctions</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="auctionForm">
          <div class="mb-3">
            <% @auctions.each do |auction| %>
              <div style="display: flex; flex-direction: column; gap: 10%; background: white; width: 100%; border: none;border-radius: 20px; padding: 10%;" class="mt-3 mb-3">
                <div class="mobile-car-inner">
                  <div style="flex: 1;">
                    <div style="text-align: left; color: #646d81; font-size: larger;">Auction Title</div>
                    <div style="text-align: left; color: #2B4159; font-size: x-large; font-weight: bold;"><%=auction.title%></div>
                  </div>

                  <div style="flex: 1;">
                    <div style="text-align: right; color: #646d81; font-size: larger;">Auction Lot No.</div>
                    <div style="text-align: right; color: #2B4159; font-size: x-large; font-weight: bold;"><%= auction.lot_no%></div>
                  </div>
                </div>

                <div class="mobile-car-inner">
                  <div style="flex: 1;">
                    <div style="text-align: left; color: #646d81; font-size: larger;">Start Time</div>
                    <div style="text-align: left; color: #2B4159; font-size: x-large; font-weight: bold;"><%=auction.start_time%></div>
                  </div>

                  <div style="flex: 1;">
                    <div style="text-align: right; color: #646d81; font-size: larger;">End Time</div>
                    <div style="text-align: right; color: #2B4159; font-size: x-large; font-weight: bold;"><%= auction.end_time%></div>
                  </div>
                </div>

                <div class="mobile-car-inner">
                  <div style="flex: 1;">
                    <div style="text-align: left; color: #646d81; font-size: larger;">Status</div>
                    <div style="text-align: left; color: #2B4159; font-size: x-large; font-weight: bold;"><%=humanize_status(auction.status)%></div>
                  </div>

                  <div style="flex: 1;">
                    <div style="text-align: right; color: #646d81; font-size: larger;">Cars added</div>
                    <div style="text-align: right; color: #2B4159; font-size: x-large; font-weight: bold;"><%= auction.cars.count%></div>
                  </div>
                </div>

                <div class="mobile-car-inner">
                  <button class="btn btn-primary confirm-auction" style="background: #2B4159; color: white; border: none; border-radius: 25px; width: 100%;" data-auction-id="<%= auction.id %>">Confirm Auction</button>
                  
                </div>
              </div>
            <% end %>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const addToAuctionButtons = document.querySelectorAll('.add-to-auction');
    const confirmAuctionButtons = document.querySelectorAll('.confirm-auction');

    addToAuctionButtons.forEach(function(button) {
      button.addEventListener('click', function() {
        const carId = button.getAttribute('data-car-id');
        document.getElementById('selected-car-id').value = carId; // Set the selected car ID in the hidden input field
        $('#auctionModal').modal('show');
      });
    });

    confirmAuctionButtons.forEach(function(button) {
      button.addEventListener('click', function(event) {
        event.preventDefault(); // Prevent default form submission
        const carId = document.getElementById('selected-car-id').value; // Retrieve the selected car ID from the hidden input field
        const auctionId = button.getAttribute('data-auction-id');
        const token = document.querySelector('meta[name="csrf-token"]').getAttribute('content');

        fetch(`/cars/${carId}/add_to_auction`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'X-CSRF-Token': token
          },
          body: JSON.stringify({ car_id: carId, auction_id: auctionId })
        })
        .then(response => {
          if (!response.ok) {
            throw new Error('Network response was not ok');
          }
          return response.text();
        })
        .then(data => {
          const modalBody = document.querySelector('.modal-body');
          modalBody.insertAdjacentHTML('beforeend', data);
          $('#auctionModal').modal('hide');
          location.reload();
        })
        .catch(error => console.error('Error:', error));
      });
    });
  });
</script>

app/views/auctions/_form.html.erb
<%= form_with(model: auction) do |form| %>
  <% if auction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(auction.errors.count, "error") %> prohibited this auction from being saved:</h2>

      <ul>
        <% auction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/auctions/all_auctions.html.erb
<style>
  .auction-heading-style{
    color: #2B4159;
    font-weight: bold;
  }

  .auctions-heading-container{
    display: flex;
    align-items: center;
    justify-content: space-between;
    width: 100%;
    padding-left: 5%;
    padding-right: 5%;
  }

  .auction-main{
    width: 85%;
    display: flex;
    background-color: #F4F7FE;
    flex-direction: column;
  }

  .inner_box{
    display: flex;
    flex-direction: column;
    padding: 2%;
    background: white;
    border: none;
    border-radius: 5%;
    width: 25%;
    box-shadow: 0 4px 11px 10px rgba(0, 0, 0, 0.1);
  }

  .pagination-container {
    display: flex;
    justify-content: center;
  }

  .pagination {
    display: inline-block;
  }

  .pagination li {
    display: inline;
  }

  .pagination a {
    position: relative;
    line-height: 1.428571429;
  }


  @media screen and (max-width: 768px) {
    .inner_box {
      width: 90%;
    }
  }

  @media only screen and (max-width: 768px) {
    .auction-main {
      width: 100%;
    }

    .auctions-heading-container{
      flex-direction: column;
    }
  }
</style>

<div class="parent-container">
  <div class="content-wrapper">
    <div class="menu-bar">
      <%= render 'admin-shared/admin-side-bar' %>    
    </div>

    <div class="auction-main">
      <div class="auctions-heading-container">
        <h1 class="auction-heading-style">All Auction</h1>

        <%= form_tag(all_auctions_auctions_path, method: :get, class: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search by Auction Title", class: "rounded-input" %>
          <%= submit_tag "Search", class: "btn btn-secondary btn-block rounded-button" %>
        <% end %>
      </div>

      <div class="mb-5" style="display: flex; flex-wrap: wrap; gap: 1%; justify-content: center">
        <% @auctions.each do |auction| %>
          <div class="inner_box mt-5">
            <div style="display: flex;">
              <div style="flex: 1;">
                <div style="text-align: left; color: #646d81; font-size: larger;">Auction Title</div>
                <div style="text-align: left; color: #2B4159; font-size: x-large; font-weight: bold;"><%=auction.title%></div>
              </div>

              <div style="flex: 1;">
                <div style="text-align: right; color: #646d81; font-size: larger;">Auction Lot No.</div>
                <div style="text-align: right; color: #2B4159; font-size: x-large; font-weight: bold;"><%= auction.lot_no%></div>
              </div>
            </div>

            <div class="mt-3" style="display: flex;">
              <div style="flex: 1;">
                <div style="text-align: left; color: #646d81; font-size: larger;">Start Time</div>
                <div style="text-align: left; color: #2B4159; font-size: x-large; font-weight: bold;"><%= auction.start_time.strftime("%Y-%m-%d %H:%M:%S") %></div>
              </div>

              <div style="flex: 1;">
                <div style="text-align: right; color: #646d81; font-size: larger;">End Time</div>
                <div style="text-align: right; color: #2B4159; font-size: x-large; font-weight: bold;"><%= auction.end_time.strftime("%Y-%m-%d %H:%M:%S") %></div>
              </div>
            </div>

            <div class="mt-3" style="display: flex;">
              <div style="flex: 1;">
                <div style="text-align: left; color: #646d81; font-size: larger;">Status</div>
                <div style="text-align: left; color: #2B4159; font-size: x-large; font-weight: bold;"><%=humanize_status(auction.status)%></div>
              </div>

              <div style="flex: 1;">
                <div style="text-align: right; color: #646d81; font-size: larger;">Cars count</div>
                <div style="text-align: right; color: #2B4159; font-size: x-large; font-weight: bold;"><%= auction.cars.count%></div>
              </div>
            </div>

            <div class="mobile-car-inner button-container mt-3" style="display: flex;">
              <button class="btn btn-primary add-to-auction" style="background: #2B4159; color: white; width: 100%; border: none; border-radius: 25px; height: 40px;" data-toggle="modal" data-target="#auctionDetailsModal" data-auction-id="<%= auction.id %>"> Car Details </button>
            </div>
          </div>
        <% end %>
      </div> 


      <div class="pagination-container">
        <%= will_paginate @auctions %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="auctionDetailsModal" tabindex="-1" role="dialog" aria-labelledby="auctionDetailsModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div style="background: #F4F7FE;" class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="auctionDetailsModalLabel">Auction Cars</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div id="carsList"></div>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function() {
    $('.add-to-auction').click(function() {
      var auctionId = $(this).data('auction-id');

      $.ajax({
        url: '/auctions/' + auctionId + '/cars',
        type: 'GET',
        success: function(data) {
          $('#carsList').html(data);
          $('#auctionDetailsModal').modal('show'); // Manually trigger the modal to show
        },
        error: function() {
          alert('Error fetching associated cars.');
        }
      });
    });
  });
</script>

app/views/auctions/edit.html.erb
<h1>Editing auction</h1>

<%= render "form", auction: @auction %>

<br>

<div>
  <%= link_to "Show this auction", @auction %> |
  <%= link_to "Back to auctions", auctions_path %>
</div>

app/views/auctions/index.html.erb
<style>
  .table-responsive {
    overflow-x: auto;
    max-width: 100%;
  }

  .table {
    width: 100%;
  }

  .table th,
  .table td {
    padding: 8px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  .custom-input{
    width: 100%;
    height: 45px;
    padding: 10px;
    border: none;
    background: #F4F7FE;
    color: black;
    border-radius: 10px;
  }

  input[type="datetime-local"] {
    width: 100%;
    padding: 10px;
    box-sizing: border-box;
    font-size: 16px;
    margin-bottom: 10px;
  }

  input[type="submit"] {
    background-color: #2B4159;
    color: white;
    width: 100%;
    border: none;
    border-radius: 25px;
    height: 40px;
    cursor: pointer;
    transition: background-color 0.3s ease;
  }

  input[type="submit"]:hover {
    background-color: #1E2D3E;
  }

  .auction-outer-div{
    width: 100%;
    display: flex;
    padding: 2%;
    gap: 2%
  }

  .live-auction-inner{
    width: 60%;
    padding: 2%;
    background: white;
    border-radius: 20px;
  }

  .sold-cars-inner{
    width: 40%;
    padding: 2%;
    background: white;
    border-radius: 20px;
  }

  .create-auction-inner{
    width: 40%;
    padding: 2%;
    background: white;
    border-radius: 20px;
  }

  .auction-heading-style{
    color: #2B4159;
    font-weight: bold;
  }

  .add-stock-auction{
    width: 60%;
    padding: 2%;
    background: white;
    border-radius: 20px;
  }

  .auction-main{
    width: 85%;
    display: flex;
    background-color: #F4F7FE;
    flex-direction: column;
  }

  @media only screen and (max-width: 768px) {

    .auction-outer-div{
      flex-direction: column;
    }

    .auction-cars-table{
      display: none;
    }

    .sold-cars-inner, .create-auction-inner, .live-auction-inner, .add-stock-auction, .auction-main {
      width: 100%;
    }
  }
</style>

<div class="parent-container">
  <div class="content-wrapper">
    <div class="menu-bar">
      <%= render 'admin-shared/admin-side-bar' %>    
    </div>

    <div class="auction-main">
      <div style="display: flex; width: 100%; padding-left: 5%;" class="">
        <h1 class="auction-heading-style">Auction</h1>
      </div>  

      <div class="auction-outer-div">
        <div class="create-auction-inner mt-3">
          <h3 class="mt-3 auction-heading-style">Create An Auction</h3>
          <div>
            <%= form_with(model: Auction, url: auctions_path) do |form| %>
              <div>
                <%= form.text_field :title, class: "custom-input", placeholder: "Enter title", required: true %>
              </div>

              <div class="mt-4">
                <%= form.text_field :lot_no, class: "custom-input", placeholder: "Enter Lot No.", required: true %>
              </div>

              <div class="mt-4">
                <%= form.label :start_time %>
                <%= form.datetime_field :start_time, class: "start-time custom-input", placeholder: "Select start time", required: true %>
              </div>

              <div>
                <%= form.label :end_time %>
                <%= form.datetime_field :end_time, class: "end-time custom-input", placeholder: "Select end time", required: true %>
              </div>
              
              <div>
                <%= form.submit 'Create An Auction', style: "background: #2B4159; color: white; width: 100%; border: none; border-radius: 25px; height: 40px;" %>    
              </div>
            <% end %>
          </div>
        </div>

        <div  class="add-stock-auction mt-3">
          <div style="display: flex; align-items: center; justify-content: space-between">
            <h3 class="mt-3 auction-heading-style">Add Stock To Auction</h3>
            <%= link_to "View All", cars_path, style: "text-decoration: none; color: #2B4159;" %>
          </div>
          <div id="cars-table-container">
            <%= render partial: 'cars_table', locals: { cars: @cars } %>    
          </div>
        </div>
      </div>

      <div class="auction-outer-div mb-3">
        <div class="live-auction-inner mt-3">
          <div style="display: flex; align-items: center; justify-content: space-between">
            <h3 class="mt-3 auction-heading-style">Live Auctions</h3>
            <%= link_to "View All", all_auctions_auctions_path, style: "text-decoration: none; color: #2B4159;" %>
          </div>
          
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th>Tracking ID</th>
                  <th>Product Name</th>
                  <th>Reserve Price</th>
                  <th>Lot No.</th>
                  <th>Highest Bid</th>
                </tr>
              </thead>
              
              <tbody>
                <% @auction_cars_paginated.each do |auction_car| %>
                  <tr>
                    <td><%= auction_car.car.id %></td>
                    <td>
                      <div style="display: flex; align-items: center;">
                        <% if auction_car.car.image.attached? %>
                          <%= image_tag url_for(auction_car.car.image), class: "mr-2", style: "width: 50px; height: 35px; margin-right: 5px;" %>
                        <% else %>
                          <%= image_tag("no-image.jpg", alt: "no-image", class: "mr-2", style: "width: 50px; height: 35px; margin-right: 5px;") %>
                        <% end %>
                        <%="#{auction_car.car.make}, #{auction_car.car.model}"%>   
                      </div>
                    </td>
                    <td>£<%= auction_car.car.reserve_auction_price %></td>
                    <td><%= auction_car.auction.lot_no %></td>
                    <td>£<%= auction_car.car.bids.any? ? auction_car.car.bids.where(auction_id: auction_car.auction.id).maximum(:amount) : 0 %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <%= will_paginate @auction_cars_paginated, param_name: 'live_auction_page' %>
        </div>

        <div class="sold-cars-inner mt-3">
          <h3 class="mt-3 auction-heading-style">Sold Products</h3>
          <div>
            <% @sold_cars&.each do |car| %>
              <div class="mt-3" style="display: flex;">
                <div class="me-2" style="width: 30%">
                 <% if car.image.attached? %>
                  <%= image_tag url_for(car.image), class: "", style: "max-width: 100%; width: 100%" %>
                <%else%>
                  <%= image_tag("no-image.jpg", alt: "no-image", class: "", style: "max-width: 100%; width: 100%") %>
                <% end %> 
                </div>
                <div style="width: 70%; display: flex; flex-direction: column; justify-content: center;">
                  <h4 style="color: #2B4159; font-weight: bold;"><%="#{car.make}, #{car.model}"%></h4>
                  <h3 style="color: #2B4159; font-weight: bold;">£<%= car.reserve_auction_price%></h3>
                </div>
              </div>
            <% end %>
            <%= will_paginate @sold_cars, param_name: 'sold_page' %>
          </div>
        </div>
      </div>
  </div>
</div>

<script>
  // JavaScript for validating date and time
  document.addEventListener('DOMContentLoaded', function() {
    const startInput = document.querySelector('.start-time');
    const endInput = document.querySelector('.end-time');

    startInput.addEventListener('change', function() {
      // Prevent selecting past dates
      const startDate = new Date(startInput.value);
      const now = new Date();
      const endDate = new Date(endInput.value);
      if (startDate < now) {
        alert("Start date cannot be in the past");
        startInput.value = ''; // Clear the input
      }

      if (endDate <= startDate) {
        alert("End date must be greater than start date");
        endInput.value = ''; // Clear the input
      }
    });

    endInput.addEventListener('change', function() {
      const startDate = new Date(startInput.value);
      const endDate = new Date(endInput.value);

      // Check if end date is greater than start date
      if (endDate <= startDate) {
        alert("End date must be greater than start date");
        endInput.value = ''; // Clear the input
      }
    });
  });
</script>

app/views/auctions/index.js.erb
// app/views/auctions/index.js.erb
$("#cars-table-container").html("<%= j(render partial: 'cars_table', locals: { cars: @cars }) %>");

app/views/auctions/new.html.erb
<h1>New auction</h1>

<%= render "form", auction: @auction %>

<br>

<div>
  <%= link_to "Back to auctions", auctions_path %>
</div>

app/views/auctions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @auction %>

<div>
  <%= link_to "Edit this auction", edit_auction_path(@auction) %> |
  <%= link_to "Back to auctions", auctions_path %>

  <%= button_to "Destroy this auction", @auction, method: :delete %>
</div>