config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  get 'dashboard/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users do
    post 'approve_user', on: :member
    post 'reject_user', on: :member
    get 'preview', on: :member
  end

  get 'home/index'
  get '/car_collection', to: 'home#car_collection', as: 'car_collection'
  get '/car_search', to: 'home#car_search', as: 'car_search'
  post '/verification', to: 'users#verification', as: 'verification'
  get '/user_verification', to: 'users#user_verification', as: 'user_verification'
  get '/dashboard', to: 'dashboard#index', as: 'dashboard'
  get '/car_purchase', to: 'cars#car_purchase', as: 'car_purchase'
  get '/successful_bid', to: 'cars#successful_bid', as: 'successful_bid'
  get '/about', to: 'home#about', as: 'about'
  get '/revenue', to: 'revenues#index', as: 'revenue'
  get '/download_reports', to: 'revenues#download_reports', as: 'download_reports'
  
  resources :cars do
    post 'add_to_auction', on: :member
    post 'buy'
    post 'submit_bid'
    get 'highest_bid'
  end

  scope module: 'payments' do
    get 'create_checkout_session'
    get 'subscription'
  end

  resources :auctions do
    get 'cars', on: :member
    delete 'delete_auction_car', on: :member
    collection do
      get 'all_auctions'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  mount Sidekiq::Web => '/sidekiq'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :full_name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :user_name, presence: true, uniqueness: true

  has_one :stripe_account_detail
  has_one_attached :verification_image1
  has_one_attached :verification_image2
  has_one_attached :image

  has_many :receipts
  has_many :bids

  after_create :create_stripe_account

  enum role: { dealer: 'dealer', individual: 'individual', admin: 'admin' }
  enum admin_status: { pending: 'pending', rejected: 'rejected', approved: 'approved' }

  def address
    "#{address_line_1} #{address_line_2}, #{city}, #{state}, #{country}"
  end

  def get_revenue
    user_revenue = Receipt.where(user_id: id, created_at: 6.months.ago.beginning_of_month..Time.current.end_of_month)
                        .group("strftime('%m %Y', created_at)")
                        .sum(:amount)
    user_stat_data = {}

    (0..5).reverse_each do |i|
      month_year_key = (Time.current - i.month).strftime('%B')
      month_year_value = (Time.current - i.month).strftime('%m %Y')
      user_stat_data[month_year_key] = user_revenue[month_year_value] || 0
    end
    user_stat_data
  end

  def verification_completed?
    role == 'admin' ||
    (role == "individual" && verification_image1.attached? && verification_image2.attached? && stripe_account_detail.payment_status) ||
    (role == "dealer" && verification_image1.attached? && verification_image2.attached? && business_name.present? && vat_number.present? && breakers_licensing.present?)
  end

  private

  def create_stripe_account
    Stripe::AccountCreationService.new(self.id).account_creation
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # Custom logic for user registrations
  before_action :redirect_signed_in_user, only: [:new]
  before_action :configure_sign_up_params, only: [:create]

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :user_name])
  end

  def after_sign_up_path_for(resource)
    user_verification_path
  end

  private

  def redirect_signed_in_user
    if user_signed_in?
      redirect_to root_path, flash: "You are already signed in."
    end
  end
end

  

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # Custom logic for user sessions
  def after_sign_in_path_for(resource)
    if resource.verification_completed?
      resource.admin? ? dashboard_path : car_collection_path
    else
      user_verification_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_admin
  skip_before_action :ensure_admin, only: %i[ verification user_verification ]

  def verification
    ActiveRecord::Base.transaction do
      if @current_user.update(user_params)
        @current_user.verification_image1.attach(params[:verification_image1]) if params[:verification_image1].present?
        @current_user.verification_image2.attach(params[:verification_image2]) if params[:verification_image2].present?
        @current_user.image.attach(params[:image]) if params[:image].present?
        if params[:user][:payment_status] == "true"
          redirect_to create_checkout_session_path
        else
          redirect_to car_collection_path, notice: 'Verification submitted successfully, Our team will review your account details shortly and you will be able to buy or bid on our platform. Thanks!'
        end
      else
        redirect_to user_verification_path, notice: 'An Error Occurred'
      end
    rescue ActiveRecord::StatementInvalid => e
      # Handle database lock exception
      redirect_to user_verification_path, notice: 'Database is busy, please try again later.'
    end
  end

  def index
    if params[:search].present?
      @users = User.where("full_name LIKE ?", "%#{params[:search]}%").paginate(page: params[:page], per_page: 10)
      @mobile_users = User.where("full_name LIKE ?", "%#{params[:search]}%").paginate(page: params[:mobile_page], per_page: 1)
    else
      @users = User.paginate(page: params[:page], per_page: 10)
      @mobile_users = User.paginate(page: params[:mobile_page], per_page: 1)
    end
  end

  def preview
    @user = User.find(params[:id])
    @user_stat_data = @user.get_revenue

    respond_to do |format|
      format.js
    end
  end

  def approve_user
    @user = User.find(params[:id])
    @user.update(admin_status: "approved")
    redirect_to users_path, notice: 'User Approved'
  end

  def reject_user
    @user = User.find(params[:id])
    @user.update(admin_status: "rejected")
    redirect_to users_path, notice: 'User Rejected'
  end

  def user_verification
  end

  private

  def user_params
    params.require(:user).permit(:business_name, :vat_number, :breakers_licensing, :role, :phone_number, :address_line_1, :address_line_2, :city, :state, :country, :postcode)
  end

  def ensure_admin
    authorize! :manage, User
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user_card.html.erb
<style>
  .centered-image {
    width: 100px;
    height: 100px;
    margin-right: 5px;
    margin-left: auto;
    margin-right: auto;
    display: block;
  }

  .file-button {
    border: 2px solid #CCCCCC;
    border-radius: 10px;
    padding: 2%;
    text-align: center;
    cursor: pointer;
  }

  .file-button:hover {
    border-color: #2B4159;
  }

  .file-button input[type="file"] {
    display: none;
  }

  .custom-file{
    text-decoration: none;
    color: #2b4159;
  }

  .pagination{
    overflow: auto;
  }



</style>


<div style="display: flex; justify-content: center; flex-direction: column; width: 100%; background: white; border-radius: 20px;" class="mt-5 mb-5 preview-details">
  <div class="mt-3" style="text-align: center;">
    <% if user.image.attached? %>
      <%= image_tag url_for(user.image), class: "mr-2 centered-image rounded-circle", alt: "user-image" %>
    <% else %>
      <%= image_tag("no-image.jpg", alt: "no-image", class: "mr-2 centered-image rounded-circle") %>
    <% end %>
    <h2><%= user.full_name %></h2>
    <p><%= humanize_status(user.role) %></p>
  </div>
  
  <div class="p-3">
    <h3 style="color: #2B4159; font-weight: bold;" class="mt-3">Contact Info</h3>

    <div class="mt-3" style="display: flex; align-items: center;">
      <%= image_tag("sms.png", alt: "no-image", class: "mr-2", style: "width: 35px; height: 25px; margin-right: 5px;") %>
      <%= user.email %>      
    </div>

    <div class="mt-3" style="display: flex; align-items: center;">
      <%= image_tag("call.png", alt: "no-image", class: "mr-2", style: "width: 35px; height: 25px; margin-right: 5px;") %>
      <%= user.phone_number %>      
    </div>

    <div class="mt-3" style="display: flex; align-items: center;">
      <%= image_tag("map.png", alt: "no-image", class: "mr-2", style: "width: 35px; height: 25px; margin-right: 5px;") %>
      <%= user.address %>      
    </div>

    <div class="mt-3" style="display: flex; justify-content: center;">
      <canvas id="myMobileChart" data-user-stat="<%= user.get_revenue.to_json %>"></canvas>
    </div>

    <div class="file-button mt-3">
      <label for="verification_image1" style="display: flex; align-items: center;">
        <%= image_tag("profile.png", alt: "identification-icon", class: "logo", style: "width: 35px; height: 35px;") %>
        <%if user.verification_image1.attached? %>
          <%= link_to "Proof Of Identification", url_for(user.verification_image1), target: "_blank", class: "custom-file" %>
        <% else %>
          No File Attached
        <% end %>
        <br>
      </label>
    </div>

    <div class="file-button mt-3">
      <label for="verification_image1" style="display: flex; align-items: center;">
        <%= image_tag("house.png", alt: "identification-icon", class: "logo", style: "width: 35px; height: 35px;") %>
        <%if user.verification_image1.attached? %>
          <%= link_to "Proof Of Address", url_for(user.verification_image2), target: "_blank", class: "custom-file" %>
        <% else %>
          No File Attached
        <% end %>
        <br>
      </label>
    </div>


    <div class="mt-4" style="display: flex; flex-direction: column; gap: 2%;">
      <%= button_to 'Approve', approve_user_user_path(user), method: :post, class: 'btn btn-primary add-to-auction', style: 'background: #2B4159; color: white; width: 100%; border: none; border-radius: 25px;' %>
      <%= button_to 'Reject', reject_user_user_path(user), method: :post, class: 'mt-3 btn btn-primary add-to-auction', style: 'background: #DBE0EB; color: #2B4159; width: 100%; border: none; border-radius: 25px;' %>
    </div>
  </div>
</div>


<script>
  // Function to render the chart with responsive width
  function renderChart(canvasId, xValues, yValues, barColor) {
    var canvas = document.getElementById(canvasId);
    var ctx = canvas.getContext('2d');

    // Set canvas dimensions based on the parent container's width
    canvas.width = canvas.parentElement.offsetWidth;
    canvas.height = canvas.width * 0.6; // Maintain aspect ratio

    var myChart = new Chart(ctx, {
      type: "bar",
      data: {
        labels: xValues,
        datasets: [{
          backgroundColor: barColor,
          data: yValues
        }]
      },
      options: {
        legend: { display: false },
        title: {
          display: true,
          text: "Performance",
          fontColor: "#2B4159",
          fontSize: 18,
          fontStyle: "bold"
        },
        scales: {
          xAxes: [{
            ticks: {
              fontColor: "#2B4159"
            },
            gridLines: {
              display: false
            }
          }],
          yAxes: [{
            display: false // Hide y-axis labels
          }]
        },
        onHover: function(event, chartElement) {
          event.target.style.cursor = chartElement[0] ? 'pointer' : 'default';
        }
      }
    });

    myChart.data.datasets[0].hoverBackgroundColor = "#2B4159";
    myChart.update();
  }

  var graph = document.getElementById('myMobileChart');
  var data = JSON.parse(graph.getAttribute('data-user-stat'));
  var months = Object.keys(data);
  var amounts = Object.values(data);

  // Render the chart on page load
  console.log(months);
  console.log(amounts);
  document.addEventListener('DOMContentLoaded', function() {
    renderChart("myMobileChart", months, amounts, "#DBE0EB");
  });
</script>

app/views/users/_users-table.html.erb
<style>
  .row-style{
    border-style: none !important;
    background: white ;
    border: transparent;
  }

  .users-display-table{
    display: contents;
    width: 100%;
  }

  .mobile-user-container{
    display: none;
  }

  @media only screen and (max-width: 768px) {
    .users-display-table{
      display: none;
    }

    .mobile-user-container{
      display: flex;
      width: 100%;
      flex-direction: column;
      justify-content: center;
      padding: 5%;
    }

  }
</style>
<div class="users-display-table">
  <div class="table-responsive" style="width: 90%;">
    <table class="table">
      <thead>
        <tr style="border: transparent;" >
          <th>Name</th>
          <th>Email</th>
          <th>Contact Number</th>
          <th>Status</th>
          <th></th>
        </tr>
      </thead>
      <tbody style="border: transparent;">
        <% @users&.each do |user| %>
          <tr class="row-style user-row" data-user-id="<%= user.id %>">
            <td>

              <div style="display: flex; align-items: center;">
                <% if user.image.attached? %>
                  <%= image_tag url_for(user.image), class: "mr-2 rounded-circle", style: "width: 50px; height: 35px; margin-right: 5px;" %>
                <% else %>
                  <%= image_tag("no-image.jpg", alt: "no-image", class: "mr-2", style: "width: 50px; height: 35px; margin-right: 5px;") %>
                <% end %>
                <a style="text-decoration: none; color: #2b4159; " href="#" class="user-name" data-user-id="<%= user.id %>"><%= user.full_name %></a>     
              </div>

              

            </td>
            <td><%= user.email%></td>
            <td><%= user.phone_number%></td>
            <td><%= humanize_status(user.admin_status) %></td>
            <td>
              <div style="display: flex; gap: 2%;">
        <%= button_to 'Approve', approve_user_user_path(user), method: :post, class: 'btn btn-primary add-to-auction', style: 'background: #2B4159; color: white; width: 100%; border: none; border-radius: 25px;' %>
        <%= button_to 'Reject', reject_user_user_path(user), method: :post, class: 'btn btn-primary add-to-auction', style: 'background: #2B4159; color: white; width: 100%; border: none; border-radius: 25px;' %>
      </div>
            </td>
          </tr>
        <% end %>

        <% if @users.blank? %>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <%= will_paginate @users %>
</div>

<div class="mobile-user-container">
  <% @mobile_users&.each do |user| %>
    <%= render 'user_card', user: user %>
  <% end %>
  <div>
    <%= will_paginate @mobile_users, param_name: 'mobile_page' %>
  </div>
</div>

app/views/users/_users_preview.html.erb
<style>
  .centered-image {
    width: 100px;
    height: 100px;
    margin-right: 5px;
    margin-left: auto;
    margin-right: auto;
    display: block;
  }

  .file-button {
    border: 2px solid #CCCCCC;
    border-radius: 10px;
    padding: 2%;
    text-align: center;
    cursor: pointer;
  }

  .file-button:hover {
    border-color: #2B4159;
  }

  .file-button input[type="file"] {
    display: none;
  }

  .custom-file{
    text-decoration: none;
    color: #2b4159;
  }



</style>

<script>
  function renderChart(xValues, yValues, barColor) {
    var canvas = document.getElementById("myChart");
    var containerWidth = canvas.parentElement.offsetWidth * 0.6; // Setting canvas width to 60% of its container's width
    canvas.setAttribute('width', containerWidth); // Set canvas width attribute
    canvas.height = containerWidth * 0.6; // Adjusting canvas height to maintain aspect ratio (change as needed)

    var ctx = canvas.getContext('2d');
    var myChart = new Chart(ctx, {
      type: "bar",
      data: {
        labels: xValues,
        datasets: [{
          backgroundColor: barColor,
          data: yValues
        }]
      },
      options: {
        legend: { display: false },
        title: {
          display: true,
          text: "Performance",
          fontColor: "#2B4159",
          fontSize: 18,
          fontStyle: "bold"
        },
        scales: {
          xAxes: [{
            ticks: {
              fontColor: "#2B4159"
            },
            gridLines: {
              display: false
            }
          }],
          yAxes: [{
            display: false // Hide y-axis labels
          }]
        },
        onHover: function(event, chartElement) {
          event.target.style.cursor = chartElement[0] ? 'pointer' : 'default';
        }
      }
    });
    
    myChart.data.datasets[0].hoverBackgroundColor = "#2B4159";
    myChart.update();
  }

  var graph = document.getElementById('myChart');
  var data = JSON.parse(graph.getAttribute('data-user-stat'));
  var months = Object.keys(data);
  var amounts = Object.values(data);



  renderChart(months, amounts, "#DBE0EB");
</script>

<div style="display: flex; justify-content: center; flex-direction: column; width: 100%;" class="mt-5 preview-details">
  <div class="mt-3" style="text-align: center;">
    <% if user.image.attached? %>
      <%= image_tag url_for(user.image), class: "mr-2 centered-image rounded-circle", alt: "user-image" %>
    <% else %>
      <%= image_tag("no-image.jpg", alt: "no-image", class: "mr-2 centered-image rounded-circle") %>
    <% end %>
    <h2><%= user.full_name %></h2>
    <p><%= humanize_status(user.role) %></p>
  </div>
  
  <div class="p-3">
    <h3 style="color: #2B4159; font-weight: bold;" class="mt-3">Contact Info</h3>

    <div class="mt-3" style="display: flex; align-items: center;">
      <%= image_tag("sms.png", alt: "no-image", class: "mr-2", style: "width: 35px; height: 25px; margin-right: 5px;") %>
      <%= user.email %>      
    </div>

    <div class="mt-3" style="display: flex; align-items: center;">
      <%= image_tag("call.png", alt: "no-image", class: "mr-2", style: "width: 35px; height: 25px; margin-right: 5px;") %>
      <%= user.phone_number %>      
    </div>

    <div class="mt-3" style="display: flex; align-items: center;">
      <%= image_tag("map.png", alt: "no-image", class: "mr-2", style: "width: 35px; height: 25px; margin-right: 5px;") %>
      <%= user.address %>      
    </div>

    <div class="mt-3" style="display: flex; justify-content: center;">
      <canvas id="myChart" data-user-stat="<%= @user_stat_data.to_json %>"></canvas>
    </div>

    <div class="file-button mt-3">
      <label for="verification_image1" style="display: flex; align-items: center;">
        <%= image_tag("profile.png", alt: "identification-icon", class: "logo", style: "width: 35px; height: 35px;") %>
        <%if user.verification_image1.attached? %>
          <%= link_to "Proof Of Identification", url_for(user.verification_image1), target: "_blank", class: "custom-file" %>
        <% else %>
          No File Attached
        <% end %>
        <br>
      </label>
    </div>

    <div class="file-button mt-3">
      <label for="verification_image1" style="display: flex; align-items: center;">
        <%= image_tag("house.png", alt: "identification-icon", class: "logo", style: "width: 35px; height: 35px;") %>
        <%if user.verification_image2.attached? %>
          <%= link_to "Proof Of Address", url_for(user.verification_image2), target: "_blank", class: "custom-file" %>
        <% else %>
          No File Attached
        <% end %>
        <br>
      </label>
    </div>

  </div>
  
</div>

app/views/users/index.html.erb
<style>
  .admin-user-table{
    background-color: #F4F7FE;
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 65%;
  }

  .users-heading-style{
    color: #2B4159;
    font-weight: bold;
  }

  .users-heading-container{
    display: flex;
    align-items: center;
    justify-content: space-between;
    width: 100%;
    padding-left: 5%;
    padding-right: 5%;
  }

  @media only screen and (max-width: 768px) {
    .user-preview-class{
      display: none;
    }

    .users-heading-container{
      flex-direction: column;
    }

    .admin-user-table{
      width: 100%;
    }

  }
</style>

<div class="parent-container">
  <div class="content-wrapper">
    <div class="menu-bar">
      <%= render 'admin-shared/admin-side-bar' %>
    </div>

    <div class="admin-user-table">
      <div class="users-heading-container">
        <h1 class="users-heading-style">Users List</h1>
        <%= form_tag(users_path, method: :get, class: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search by User's Name", class: "rounded-input" %>
          <%= submit_tag "Search", class: "btn btn-secondary btn-block rounded-button" %>
        <% end %>
      </div>
      <%= render 'users-table' %>
    </div>

    <div style="background: white;" class="preview-break-2 user-preview-class">
      Preview
    </div>
</div>

<script>
  $(document).ready(function() {
    function previewFirstUser() {
      var firstUserId = $('.user-row:first').data('user-id'); // Get the ID of the first user
      if (firstUserId) {
        $.ajax({
          url: "/users/" + firstUserId + "/preview",
          type: "GET",
          dataType: "script"
        });
      }
    }

    // Call the function to preview the first user when the document is ready
    previewFirstUser();

    // Function to handle click on user name
    $(".user-name").click(function(e) {
      e.preventDefault();
      var userId = $(this).closest('.user-row').data('user-id');
      $.ajax({
        url: "/users/" + userId + "/preview",
        type: "GET",
        dataType: "script"
      });
    });
  });
</script>

app/views/users/preview.js.erb
$(".preview-break-2").html("<%= j render 'users_preview', user: @user %>");