config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  get 'dashboard/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users do
    post 'approve_user', on: :member
    post 'reject_user', on: :member
    get 'preview', on: :member
  end

  get 'home/index'
  get '/car_collection', to: 'home#car_collection', as: 'car_collection'
  get '/car_search', to: 'home#car_search', as: 'car_search'
  post '/verification', to: 'users#verification', as: 'verification'
  get '/user_verification', to: 'users#user_verification', as: 'user_verification'
  get '/dashboard', to: 'dashboard#index', as: 'dashboard'
  get '/car_purchase', to: 'cars#car_purchase', as: 'car_purchase'
  get '/successful_bid', to: 'cars#successful_bid', as: 'successful_bid'
  get '/about', to: 'home#about', as: 'about'
  get '/revenue', to: 'revenues#index', as: 'revenue'
  get '/download_reports', to: 'revenues#download_reports', as: 'download_reports'
  
  resources :cars do
    post 'add_to_auction', on: :member
    post 'buy'
    post 'submit_bid'
    get 'highest_bid'
  end

  scope module: 'payments' do
    get 'create_checkout_session'
    get 'subscription'
  end

  resources :auctions do
    get 'cars', on: :member
    delete 'delete_auction_car', on: :member
    collection do
      get 'all_auctions'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  mount Sidekiq::Web => '/sidekiq'
end

app/views/shared/_bid_modal.html.erb
<!-- app/views/shared/_bid_modal.html.erb -->

<!-- Modal -->
<div class="modal fade" id="bidModal" tabindex="-1" role="dialog" aria-labelledby="bidModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content bid-modal-wrapper">
      <div class="modal-header bid-modal-header">
        <h5 class="modal-title bid-modal-title" id="bidModalLabel">Place Bid</h5>
        <button type="button" class="close bid-modal-close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body bid-modal-body">
        <p class="last-highest-bid-label">Last Highest Bid: <span id="lastHighestBid"></span></p>
        <%= form_with(method: :post, remote: true, class: 'bid-submit-form') do |form| %>
          <div class="form-group">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" autocomplete="off">
            <%= form.label :bid_amount, 'Bid Amount', class: 'bid-label'%>
            <%= form.number_field :bid_amount, class: 'form-control', required: true, id: 'bid_amount_field', min: '0.01' %>
          </div>
          <%= form.submit 'Submit Bid', class: 'btn btn-primary bid-button mt-2' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script>

  $(document).on("click", "#bidButton", function() {
    var carId = $(this).data("car-id");
    $('#bidModal').data('car-id', carId);
    $('#bidModal').modal('show');
  });
  
  $('#bidModal').on('shown.bs.modal', function(event) {
    var carId = $(this).data("car-id");
    $.ajax({
      url: 'cars/' + carId + '/highest_bid',
      method: 'GET',
      success: function(response) {
        if (response.error) {
          $('#bidModal').modal('hide');
          alert(response.error);
        } else {
          var bid_amount = response.highest_bid_amount
          $('#lastHighestBid').text('£' + bid_amount);
          $('#bid_amount_field').val(bid_amount + 1);
          $('#bid_amount_field').attr('min', bid_amount + 1);
          $('.bid-submit-form').attr('action', 'cars/' + carId + '/submit_bid');
          $('#bidModal').modal('show');
        }
      }
    });
  });
</script>

app/views/shared/_footer.html.erb
<style>
  .footer-container {
    padding: 1%;
    display: flex;
    align-items: center;
    justify-content: space-between;
    flex-wrap: wrap;
    width: 100%;
    position: relative;
    z-index: 1;
    height: 75px;
    background-color: white;
  }

  .footer-brand {
    display: flex;
    align-items: center;
  }

  @media only screen and (max-width: 768px) {
    .footer-container {
      flex-direction: column;
      height: auto;
    }

    .footer-icons{
      margin-top: 25px;
    }

    .footer-brand {
      margin-top: 3%;
    }
  }

  .text {
    margin-left: 10px;
    font-weight: bold;
  }

  .footer-links {
    display: flex;
    align-items: center;
  }

  .footer-links a {
    margin: 0 10px;
    color: black;
    text-align: center;
    text-decoration: none;
    font-size: 15px;
    font-weight: bold;
  }
</style>


<div class="footer-container">
  <div class="footer-brand">
    <%= image_tag("logo.png", alt: "Logo", class: "logo") %>
    <div class="text">
      <div class="line1">GRANITE</div>
      <div class="line2">Auctions</div>
    </div>
  </div>

  <div>
    <p class="text">@ 2024 Granite Auctions, Inc. All rights reserved.</p>
  </div>

  <div class="footer-links">
    <a href="#terms">Terms</a>
    <a href="#privacy">Privacy</a>
    <a href="#contact">Contact</a>
  </div>

  <div class="footer-icons">
    <%= image_tag("Vector.png", alt: "Logo", class: "logo") %>
    <%= image_tag("facebook.png", alt: "Logo", class: "logo") %>
    <%= image_tag("twitter.png", alt: "Logo", class: "logo") %>
    <%= image_tag("instagram.png", alt: "Logo", class: "logo") %>
    <%= image_tag("linkedin.png", alt: "Logo", class: "logo") %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="topnav" id="myTopnav">
  <div class="nav-brand">
    <%= image_tag("logo.png", alt: "Logo", class: "logo") %>
    <div class="text">
      <div class="line1">GRANITE</div>
      <div class="line2">Auctions</div>
    </div>
  </div>

  <% if user_signed_in? %>
    <%if current_user&.admin? %>
      <%= link_to dashboard_path, class: "mobile-only-menu" do %>
        <%= image_tag("category.png", alt: "Logo", class: "logo", style: "width: 20px; padding: 2%;") %>Dashboard
      <% end %>

      <%= link_to revenue_path, class: "mobile-only-menu" do %>
        <%= image_tag("empty-wallet.png", alt: "Logo", class: "logo", style: "width: 25px; padding: 2%;") %>Revenue</a>
      <% end %>

      <%= link_to cars_path, class: "mobile-only-menu" do %>
        <%= image_tag("car.png", alt: "Logo", class: "logo", style: "width: 25px; padding: 2%;") %>Stock
      <% end %>

      <%= link_to auctions_path, class: "mobile-only-menu" do %>
        <%= image_tag("judge.png", alt: "Logo", class: "logo", style: "width: 25px; padding: 2%;") %>Auction
      <% end %>

      <%= link_to users_path, class: "mobile-only-menu" do %>
        <%= image_tag("profile-2user.png", alt: "Logo", class: "logo", style: "width: 25px; padding: 2%;") %>Users
      <% end %>

      <%= link_to new_car_path, class: "mobile-only-menu" do %>
        <%= image_tag("car.png", alt: "Logo", class: "logo", style: "width: 25px; padding: 2%;") %>Add Car To Stock
      <% end %>

    <% else %>
      <a href="/car_collection">Cars</a>
      <% unless current_user.verification_completed? %>
        <a href="<%= user_verification_path %>">Account Verification</a>
      <% end %>
    <% end %>
    
    <%= link_to(image_tag("profile-tick.png", alt: "Logo", class: "logo") + " Logout", destroy_user_session_path, method: :delete, class: "signup-button mobile-only-menu") %>

  <% else %>
    <a href="<%= root_path %>">Home</a>
    <a href="<%= about_path %>">About</a>
    <a href="/car_collection">Cars</a>
    <a href="/users/sign_up" class="signup-button mobile-only-menu"> Sign Up </a>
    <a href="/users/sign_in" class="signup-button mobile-only-menu"> Login </a>
  <% end %>

  <div class="nav-buttons">
    <% if user_signed_in? %>
      <%= link_to(image_tag("profile-tick.png", alt: "Logo", class: "logo") + " Logout", destroy_user_session_path, method: :delete, class: "signup-button") %>
    <% else %>
      <a href="/users/sign_up" class="signup-button"> <%= image_tag("profile.png", alt: "Logo", class: "logo") %> Sign Up </a>
      <a href="/users/sign_in" class="signup-button"> <%= image_tag("profile-tick.png", alt: "Logo", class: "logo") %> Login </a>
    <% end %>
  </div>


  <a href="javascript:void(0);" class="icon" onclick="myFunction()">
    <i class="fa fa-bars"></i>
  </a>
</div>

<script>
function myFunction() {
  var x = document.getElementById("myTopnav");
  if (x.className === "topnav") {
    x.className += " responsive";
  } else {
    x.className = "topnav";
  }
}
</script>