config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  get 'dashboard/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resources :users do
    post 'approve_user', on: :member
    post 'reject_user', on: :member
    get 'preview', on: :member
  end

  get 'home/index'
  get '/car_collection', to: 'home#car_collection', as: 'car_collection'
  get '/car_search', to: 'home#car_search', as: 'car_search'
  post '/verification', to: 'users#verification', as: 'verification'
  get '/user_verification', to: 'users#user_verification', as: 'user_verification'
  get '/dashboard', to: 'dashboard#index', as: 'dashboard'
  get '/car_purchase', to: 'cars#car_purchase', as: 'car_purchase'
  get '/successful_bid', to: 'cars#successful_bid', as: 'successful_bid'
  get '/about', to: 'home#about', as: 'about'
  get '/revenue', to: 'revenues#index', as: 'revenue'
  get '/download_reports', to: 'revenues#download_reports', as: 'download_reports'
  
  resources :cars do
    post 'add_to_auction', on: :member
    post 'buy'
    post 'submit_bid'
    get 'highest_bid'
  end

  scope module: 'payments' do
    get 'create_checkout_session'
    get 'subscription'
  end

  resources :auctions do
    get 'cars', on: :member
    delete 'delete_auction_car', on: :member
    collection do
      get 'all_auctions'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  mount Sidekiq::Web => '/sidekiq'
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :category
  belongs_to :salvage_category

  has_many :auction_cars
  has_many :auctions, through: :auction_cars
  has_many :bids
  has_one :receipt

  has_one_attached :image

  validates :make, presence: true
  validates :model, presence: true

  after_create :create_stripe_product

  scope :available, -> { where(sold: false) }

  scope :sold_cars, -> { where(sold: true) }
  
  scope :active, -> { where(sold: false) }

  scope :car_by_year, lambda { |years|
    where('year IN (?)', years)
  }

  scope :car_by_location, lambda { |location|
    where('location LIKE ?', location)
  }

  scope :car_by_category, lambda { |category_ids|
    where('category_id IN (?)', category_ids)
  }


  scope :by_category_name, ->(category_name) {
    joins(:category)
      .where("LOWER(categories.name) = ?", category_name.downcase)
  }

  scope :car_by_salvage_category, lambda { |salvage_ids|
    where('salvage_category_id IN (?)', salvage_ids)
  }

  scope :car_by_make_model, ->(makes) {
    where(
      makes.map { |_make| "make LIKE ?" }.join(' OR '), *makes.map { |make| "%#{make}%" }
      )
  }

  scope :car_by_model, ->(models) {
    where(
      models.map { |_model| "model LIKE ?" }.join(' OR '), *models.map { |model| "%#{model}%" }
      )
  }

  scope :car_by_price_range, ->(price_range) {
    case price_range
    when "< £2500"
      where("buy_now_price < ?", 2500)
    when "£2501 - £5000"
      where(buy_now_price: 2501..5000)
    when "£5001 - £10,000"
      where(buy_now_price: 5001..10000)
    when "£10,001 - £20,000"
      where(buy_now_price: 10001..20000)
    when ">£20,001"
      where("buy_now_price > ?", 20001)
    else
      all
    end
  }

  scope :in_progress_auction_cars, -> { joins(:auctions).where(auctions: { status: 'in_progress' }) }

  def self.apply_filters(params)
    cars = active
    cars = cars.car_by_make_model(Array.wrap(params[:make])) if params[:make].present?
    cars = cars.car_by_model(Array.wrap(params[:model])) if params[:model].present?
    cars = cars.car_by_year(params[:year]) if params[:year].present?
    cars = cars.car_by_category(params[:category]) if params[:category].present?
    cars = cars.car_by_salvage_category(params[:salvage]) if params[:salvage].present?
    cars = cars.car_by_price_range(params[:price_range]) if params[:price_range].present?
    cars = cars.car_by_location(params[:city]) if params[:city].present?
    cars = cars.by_category_name(params[:name]) if params[:name].present?
    cars
  end

  def auction_end_time
    auctions.current.first.end_time
  end

  def create_stripe_product
    stripe_product = Stripe::Product.create({
      name: "#{make}, #{model}",
      description: description,
      default_price_data: {
        currency: "gbp",
        unit_amount: calculate_final_price_in_cents.to_i
      },
      metadata: {
        car_id: id,
      }
    })
    update(stripe_product_id: stripe_product.id)
  end

  def create_stripe_car_price
    Stripe::Price.create({
      currency: 'gbp',
      unit_amount: calculate_final_price_in_cents.to_i,
      product: stripe_product_id
    })
  end

  def calculate_final_price_in_cents
    (buy_now_price + (0.2 * buy_now_price) + delivery_cost) * 100
  end

  def bids_for_active_auction
    active_auction = auctions.current.first
    active_auction.present? ? active_auction.bids.where(car_id: id) : []
  end

  def highest_bid_amount
    bids_for_active_auction.map(&:amount).max || reserve_auction_price
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  include CarPaymentConcern
  before_action :ensure_admin, except: %i[buy highest_bid car_purchase submit_bid successful_bid]
  before_action :verify_user_status, only: %i[buy car_purchase]
  before_action :set_car, only: %i[edit update destroy show add_to_auction highest_bid submit_bid buy]

  def index
    @car = Car.new
    if params[:search].present?
      search_term = "%#{params[:search]}%"
      @cars = Car.where("make LIKE ? OR model LIKE ?", search_term, search_term).paginate(page: params[:page], per_page: 10)
      else
      @cars = Car.paginate(page: params[:page], per_page: 10)
    end
    render :index
  end

  def destroy
    begin
      if @car.destroy
        redirect_to cars_path, notice: 'Car was successfully destroyed.'
      else
        redirect_to cars_path, notice: 'Car was not created.'
      end
    rescue => e
      redirect_to cars_path, notice: "An error occurred: #{e.message}"
    end
  end

  def create
    begin
      @car = Car.new(car_params)
      @car.image.attach(params[:image]) if params[:image].present?

      if @car.save
        redirect_to cars_path, notice: 'Car was successfully created.'
      else
        redirect_to cars_path, notice: 'Car was not created.'
      end
    rescue => e
      redirect_to cars_path, notice: "An error occurred: #{e.message}"
    end
  end

  def new
    @car = Car.new
  end

  def edit
  end

  def show
  end

  def update
    begin
      @car.image.attach(params[:image]) if params[:image].present?
      if @car.update(car_params)
        redirect_to cars_path, notice: 'Car was successfully updated.'
      else
        redirect_to cars_path, notice: 'Car was not updated.'
      end
    rescue => e
      redirect_to cars_path, notice: "An error occurred: #{e.message}"
    end
  end

  # need to discuss this further
  def add_to_auction
    begin
      @auction = Auction.find(params[:auction_id])
      return unless @car || @auction
      authorize! :create, @auction
      unless @auction.auction_cars.exists?(auction: @auction, car: @car)
        AuctionCar.create!(auction: @auction, car: @car)
      end
      flash[:success] = "Car successfully added to auction."
    rescue ActiveRecord::RecordInvalid => e
      flash[:error] = e.message
    end
    
  end

  def buy
    redirect_to payment_session.url, allow_other_host: true
  end

  def highest_bid
    verification_error = verify_user_status(true)
    render json: verification_error.present? ? verification_error : { highest_bid_amount: @car.highest_bid_amount }
  end

  def submit_bid
    auction = @car.auctions.current.first
    bid = Bid.find_or_initialize_by(car_id: @car.id, auction_id: auction.id, user_id: current_user.id)
    create_hold_amount = bid.id.blank? # only create hold amount for new bids
    bid.update(amount: params[:bid_amount])
    if create_hold_amount
      # handles the use case if we are already have the payment method Id of current user
      # directly holding the security amount against the bidding
      if current_user.payment_method_id.present?
        hold_bidding_security(current_user.payment_method_id, bid.id)
        redirect_back fallback_location: car_collection_path, notice: "Bid successful"
      else
        # in case of payment method not present, create a session for getting payment method
        # upon sucess, hold the security amount
        session = bidding_payment_session(bid)
        redirect_to session.url , allow_other_host: true
      end
    else
      redirect_back fallback_location: car_collection_path, notice: "Bid successful"
    end
  end

  def successful_bid
    session = fetch_session_data(params[:session_id])
    payment_method = session.setup_intent.payment_method
    current_user.update(payment_method_id: payment_method)
    hold_bidding_security(payment_method, session.metadata.bid_id)
    redirect_to car_collection_path, notice: "Bid successful"
  end

  def car_purchase
    if params[:success] == 'true' && handle_transaction_success
      redirect_to car_collection_path , notice: "Payment successful"
    else
      redirect_to car_collection_path, notice: 'Payment failed, please try again'
    end
  end

  private

  def car_params
    params.require(:car).permit(:make_model, :year, :engine_capacity, :kms_driven, :reserve_auction_price, :buy_now_price, :description, :salvage_category_id, :category_id, :location, :delivery_cost, :image, :make, :model)
  end

  def ensure_admin
    authorize! :manage, Car
  end

  def verify_user_status(json_response = false)
    if !current_user.verification_completed?
      if json_response
        flash[:error] = 'User verification is pending'
        return { error: 'User verification is pending'}
      end
      # return { error: 'User verification is pending'} if json_response
      redirect_to user_verification_path, notice: 'User verification is pending'
    elsif current_user.admin_status == 'pending'
      if json_response
        flash[:error] = 'User needs to be verified from admin.'
        return { error: 'User needs to be verified from admin.'}
      end
      redirect_to car_collection_path, notice: 'User needs to be verified from admin.'
    end
  end

  def set_car
    @car = Car.find(params[:id] || params[:car_id])
  end
end

app/views/cars/_cars-table.html.erb
<div style="display: contents; width: 100%">
  <table class="car-table-index">
    <thead>
      <tr>
        <th>Make Or Model</th>
        <th>Reserve Price</th>
        <th>Buy Now Price</th>
        <th>Category</th>
        <th>Delivery</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @cars&.each do |car| %>
        <tr>
          <td>
            <div style="display: flex; align-items: center;">
              <% if car.image.attached? %>
                <%= image_tag url_for(car.image), class: "mr-2 rounded-circle", style: "width: 50px; height: 35px; margin-right: 5px;" %>
              <% else %>
                <%= image_tag("no-image.jpg", alt: "no-image", class: "mr-2", style: "width: 50px; height: 35px; margin-right: 5px;") %>
              <% end %>
              <%= link_to "#{car.make}, #{car.model}", edit_car_path(car), class: "car-name" %>      
            </div>
          </td>
          <td>£<%= car.reserve_auction_price%></td>
          <td>£<%= car.buy_now_price%></td>
          <td><%= car.category.name%></td>
          <td><%= car.delivery_cost ? 'Yes' : 'No'%></td>
          <td style="display: flex; gap: 2%">
            <%= link_to "Edit", edit_car_path(car), class: "edit-item" %>
            <%= button_to "Delete", car_path(car), method: :delete, class: "delete-item", data: { confirm: "Are you sure?" } %>
          </td>
        </tr>
      <% end %>

      <%if @cars.blank? %>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      <% end %>
    </tbody>
  </table
</div>

<div class="car-display">
  <% @cars&.each do |car| %>
    <div class="mobile-car">
      <div class="mobile-car-inner">
        <div style="flex: 1;">
          <div style="text-align: left; color: #646d81; font-size: larger;">Make and Model</div>
          <div style="text-align: left; color: #2B4159; font-size: x-large; font-weight: bold;"><%= link_to "#{car.make}, #{car.model}", edit_car_path(car), style: "text-decoration: none; color: #2B4159;" %></div>
        </div>

        <div style="flex: 1;">
          <div style="text-align: right; color: #646d81; font-size: larger;">Fixed Price</div>
          <div style="text-align: right; color: #2B4159; font-size: x-large">£<%= car.reserve_auction_price%></div>
        </div>
      </div>

      <div class="mobile-car-inner">
        <div style="flex: 1;">
          <div style="text-align: left; color: #646d81; font-size: larger;">Highest Bid</div>
          <div style="text-align: left; color: #2B4159; font-size: x-large; font-weight: bold;">£ <%= car.highest_bid_amount%></div>
        </div>

        <div style="flex: 1;">
          <div style="text-align: right; color: #646d81; font-size: larger;">Category</div>
          <div style="text-align: right; color: #2B4159; font-size: x-large"><%= car.category.name%></div>
        </div>
      </div>

      <div class="mobile-car-inner button-container">
        <%= link_to "Edit", edit_car_path(car), class: "btn btn-primary btn-edit-item" %>
        <%= button_to "Delete", car_path(car), method: :delete, class: "btn btn-danger btn-delete-item" %>
      </div>
    </div>
  <% end %>
</div>

app/views/cars/_create-car-form.html.erb
<style>
  .custom-select {
    height: 25px; 
    width: 100%;
    border:none;
    border-radius: 25px;
    
  }

  .edit-color{
    background: white;
  }

  .new-color{
    background: #F4F7FE;
  }

  .custom-select-select {
    height: 40px; 
    width: 100%;
    border:none;
    border-radius: 25px;
  }

  .file-upload-box {
    border: 2px dashed #CCCCCC;
    border-radius: 10px;
    padding: 20px;
    text-align: center;
    cursor: pointer;
    width: 100%;
  }

  .file-upload-box:hover {
    border-color: #2B4159;
  }

  .file-upload-box input[type="file"] {
    display: none;
  }

  #image-preview {
    display: content;
    max-width: 100%;
    margin-top: 10px;
  }
</style>

<script>
  function previewImage(input) {
    var preview = document.getElementById('image-preview');
    preview.innerHTML = '';

    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        var img = document.createElement('img');
        img.src = e.target.result;
        img.style.maxWidth = '100%'; // Adjust image styling as needed
        img.style.maxHeight = '300px'; // Adjust image styling as needed
        preview.appendChild(img);
      }

      reader.readAsDataURL(input.files[0]);
    }
  }
</script>

<div style="padding: 5%; width: 100%;">
<h1>Car Details</h1>
<%= form_with(model: car, url: car.persisted? ? car_path(car) : cars_path) do |form| %>

  <div class="file-upload-box">
    <label for="image" style="display: flex; align-items: center;">
      <%= image_tag("note-2.png", alt: "identification-icon", class: "logo", style: "width: 50px; height: 50px;") %>Add Car Image
      <br>
      <%= form.file_field :image, id: "image", name: "image", onchange: "previewImage(this)" %>
    </label>
  </div>
  <br>

  <div id="image-preview">
    <%if car.persisted? %>
      <% if car.image.attached? %>
        <%= image_tag url_for(car.image), class: "", style: "max-width: 100%;" %>
      <% end %>
    <%end%>
  </div>

  <br>

  <div>
    <%= form.label :make %><br>
    <%= form.text_field :make, class: "custom-select #{(car.persisted? || myClass )? 'edit-color' : 'new-color'}", required: true %>
  </div>
  <br>

  <div>
    <%= form.label :model %><br>
    <%= form.text_field :model, class: "custom-select #{(car.persisted? || myClass )? 'edit-color' : 'new-color'}", required: true %>
  </div>
  <br>

  <div>
    <%= form.label :year %><br>
    <%= form.text_field :year, class: "custom-select #{(car.persisted? || myClass )? 'edit-color' : 'new-color'}", required: true %>
  </div>
  <br>

  <div>
    <%= form.label :engine_capacity %><br>
    <%= form.text_field :engine_capacity, class: "custom-select #{(car.persisted? || myClass )? 'edit-color' : 'new-color'}", required: true %>
  </div>
  <br>

  <div>
    <%= form.label :KMs_driven %><br>
    <%= form.text_field :kms_driven, class: "custom-select #{(car.persisted? || myClass )? 'edit-color' : 'new-color'}", required: true %>
  </div>
  <br>


  <div>
    <%= form.label :reserve_auction_price %><br>
    <%= form.number_field :reserve_auction_price, class: "custom-select #{(car.persisted? || myClass ) ? 'edit-color' : 'new-color'}", required: true %>
  </div>
  <br>
  <div>
    <%= form.label :buy_now_price %><br>
    <%= form.number_field :buy_now_price, class: "custom-select #{(car.persisted? || myClass ) ? 'edit-color' : 'new-color'}", required: true %>
  </div>
  <br>
  <div>
    <%= form.label :description %><br>
    <%= form.text_field :description , class: "custom-select #{(car.persisted? || myClass ) ? 'edit-color' : 'new-color'}", required: true %>
  </div>
  <br>
  <div>
    <%= form.label :salvage_category_id %>
    <br>
    <%= form.collection_select(:salvage_category_id, SalvageCategory.all, :id, :name, {}, {class: "custom-select-select #{(car.persisted? || myClass ) ? 'edit-color' : 'new-color'}"})  %>
  </div>
  <br>
  <div>
    <%= form.label :category_id %>
    <br>
    <%= form.collection_select(:category_id, Category.all, :id, :name, {}, {class: "custom-select-select #{(car.persisted? || myClass ) ? 'edit-color' : 'new-color'}"})  %>
  </div>
  <br>
  <div>
    <%= form.label :location %><br>
    <%= form.text_field :location , class: "custom-select #{(car.persisted? || myClass ) ? 'edit-color' : 'new-color'}", required: true %>
  </div>
  <br>
  <div>
    <%= form.label :delivery_cost %><br>
    <%= form.number_field :delivery_cost, class: "custom-select #{(car.persisted? || myClass ) ? 'edit-color' : 'new-color'}", required: true %>
  </div>
  <br>
  <br>
  <div>
   <%= form.submit car.persisted? ? 'Update Car' : 'Create Car', style: "background: #2B4159; color: white; width: 100%; border: none; border-radius: 25px; height: 40px;" %>
  </div>
<% end %>

</div>

app/views/cars/edit.html.erb
<div class="parent-container">
  <div class="content-wrapper">
    <div class="menu-bar">
      <%= render 'admin-shared/admin-side-bar' %>    
    </div>

    <div class="preview preview-complete">
      <%= render 'create-car-form', car: @car, myClass: nil %>    
    </div>
</div>

app/views/cars/index.html.erb
<div class="parent-container">
  <div class="content-wrapper">
    <div class="menu-bar">
      <%= render 'admin-shared/admin-side-bar' %>
    </div>
    
    <div class="car-table">

      <div class="stock-heading-main">
        <h1 class="stock-heading">Stock List</h1>

        <%= form_tag(cars_path, method: :get, class: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search by Make or Model", class: "rounded-input" %>
          <%= submit_tag "Search", class: "btn btn-secondary btn-block rounded-button" %>
        <% end %>
      </div>
      
      <div style="display: contents; width: 100%"><%= render 'cars-table' %></div>
      
      <div class="pagination-section">
        <%= will_paginate @cars %>    
      </div>
    </div>
  </div>
  <div style="background: white;" class="create-car-form preview-break-2">
      <%= render 'create-car-form', car: @car, myClass: nil %>
    </div>
</div>

app/views/cars/new.html.erb
<div class="parent-container">
  <div class="content-wrapper">
    <div class="menu-bar">
      <%= render 'admin-shared/admin-side-bar' %>    
    </div>

    <div class="preview preview-complete">
      <%= render 'create-car-form', car: @car, myClass: "custom-class" %>    
    </div>
</div>

app/views/cars/show.html.erb
<style>
  .car-show-div {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
    width: 100%;
  }

  .show-image-div, .show-description-div {
    width: 48%;
    padding: 5%;
  }

  .show-styling {
    background: white;
    padding: 5%;
    border: none;
    border-radius: 30px;
    width: 100%;
  }


@media only screen and (max-width: 768px) {
  .car-show-div {
    flex-direction: column; 
    justify-content: flex-start;
  }

  .show-image-div, .show-description-div {
    width: 100%; 
    margin-bottom: 15%;
    padding: 0%;
  }
}
</style>

<div class="parent-container">
  <div class="content-wrapper">
    <div class="menu-bar">
      <%= render 'admin-shared/admin-side-bar' %>    
    </div>

    <div class="preview preview-complete">
      <div class="car-show-div">
        <div class="show-image-div">
          <% if @car&.image.attached? %>
            <%= image_tag url_for(@car.image), class: "", style: "max-width: 100%;" %>
          <% end %>    
        </div>

        <div class="show-description-div">
          <div class="show-styling">
            <h2 style="text-align: left; color: #646d81; font-size: larger;"><%="#{@car.make}, #{@car.model}"%></h2>
            <p style="text-align: left; color: #646d81; font-size: larger;">Year: <%= @car.year %></p>
            <p style="text-align: left; color: #646d81; font-size: larger;">Engine Capacity: <%= @car.engine_capacity %></p>
            <p style="text-align: left; color: #646d81; font-size: larger;">KMs Driven: <%= @car.kms_driven %></p>
            <p style="text-align: left; color: #646d81; font-size: larger;">Reserve Auction Price: <%= @car.reserve_auction_price %></p>
            <p style="text-align: left; color: #646d81; font-size: larger;">Buy Now Price: <%= @car.buy_now_price %></p>
            <p style="text-align: left; color: #646d81; font-size: larger;" >Category: <%= @car.category.name %></p>
            <p style="text-align: left; color: #646d81; font-size: larger;">Delivery Cost: <%= @car.delivery_cost ? 'Yes' : 'No' %></p>
          </div>
        </div>
      </div>    
    </div>
  </div>
</div>